# Generated by Django 4.2.3 on 2023-07-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='uploading_date',
            field=models.DateField(max_length=10, null=True),
        ),
    ]
